language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zopfli

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

cache: bundler
sudo: true

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head