language: ruby

before_install:
  - ./spec/travis_build.sh
  - export LD_FLAGS=-L$HOME/zopfli
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/zopfli
  - export CPATH=$CPATH:$HOME/zopfli/src/zopfli

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

cache: bundler
sudo: false

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head