language: ruby

before_install:
  - ./spec/travis_build.sh > /dev/null 2>&1
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.1
  - 2.5.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

cache: bundler
sudo: false

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head
