language: ruby

before_install:
  - ./spec/travis_build.sh > /dev/null 2>&1

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

sudo: true

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head